sample_rails5_app/config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  resource :comments, only: [:index, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample_rails5_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_rails5_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  def bar_comments
    User.foo_user.comments
  end

end

sample_rails5_app/app/models/user.rb
class User < ApplicationRecord
  has_many :comments

  def self.foo_user
    first
  end

end

sample_rails5_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    User.first
  end

end

sample_rails5_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def index
    current_user.comments.all
  end

end

sample_rails5_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout :users

  def index
    User.all
  end

end

sample_rails5_app/app/helpers/application_helper.rb
module ApplicationHelper
end

sample_rails5_app/app/helpers/comments_helper.rb
module CommentsHelper
end

sample_rails5_app/app/helpers/users_helper.rb
module UsersHelper
end

sample_rails5_app/app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

sample_rails5_app/app/views/comments/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

sample_rails5_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VimRailsTutor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sample_rails5_app/app/views/layouts/users.html.erb
<div>

  <h1> Welcome to Vim-Rails Tutor </h1>

  <%= render 'shared/tim_pope' %>

  <%= link_to "New Comment", new_comment_path %>

</div>

sample_rails5_app/app/views/shared/_tim_pope.html.erb
<h2> Thank you Tim! </h2>